version: '3.8'
services:
  postgres-db:
    image: postgres:15-alpine
    container_name: neurovault-postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: neurovault_db
    ports:
      - "5433:5432" 
    restart: always