server:
  port: 8082

spring:
  application:
    name: ingestion-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/neurovault_data

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/