server:
  port: 8083

spring:
  application:
    name: cognitive-engine

  datasource:
    url: jdbc:postgresql://localhost:5433/neurovault_db
    username: root
    password: rootpassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: cognitive-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: java.util.LinkedHashMap

  ai:
    google:
      genai:
        api-key: ${API_KEY}
        chat:
          options:
            model: gemini-2.5-flash

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

application:
  security:
    jwt:
      secret-key: "5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437"